### ISSUE TITLE
C style , please serach how to solve that with python

### ISSUE THREAD

**Issue by moatasemelsayed** [MohamedFouad98/EmbeddedLinuxDiploma#1]
https://github.com/MohamedFouad98/EmbeddedLinuxDiploma/blob/5acbeeb927b312b1ff7aed43d16c85eb240174dd/Week1_python/Task1.py#L2

**Comment by MohamedFouad98** [comment]
Issue fixed.

**Comment by MohamedFouad98** [comment]
@moatasemelsayed
